-- Baseline migration for public.studio_sessions

create table if not exists public.studio_sessions (
    id bigint primary key generated by default as identity,
    created_at timestamp with time zone not null default now(),
    session_id text not null unique,
    offer jsonb,
    answer jsonb,
    ice_candidates jsonb default '[]'::jsonb,
    host_user_id uuid,
    guest_user_id uuid
);
